language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  slack:
    rooms:
      - secure: zHryAtmxuxL2sysM/mgzE11fwOjPKLWL7UzpAHy4aAtki7XKB18OOwESeGUMFGAsXW7QpCGZlUT3cjDT0cJZHDSJxK30QvZLzcuxnuhpyUur6gXBgs3KDfo2craC6bapMG1nzxYgEnMcLsqiJ/Px0P4ktQK7envSnyXHaj9SsEkJJOPhUN59i/LbmHVjU5we77egZtGD8nBp7jsFaAJOIi4xBiT44YQmVvs9S1cvCf9iTU6BkEzEAf46R+ICE+oOj54HyNycRjZBh16lTgfA21wgcg2YMi5h0Sinp0l4w6nxPPyzzpDVldyPDr4zDGon/RnCZOUtcl+UDxX/TmRprrB2EFgojoiPITGd2pNtg9aj00qq61AMoseK35rNs8aIz76xJ+NqcTqu2lbLENY7IIfqPoI4lcbxmHXbWfzyq614b9unQGQM5KttF3Hdyw+8R41/oeyp/kfdlBYtAmePA9PwtrECUSEKXa8ad66bJbsC18rwei6fWeZNTMqJcSrXUIud4GbsOb9ykaXAjjAMcmIE4BlOaC/2VKZlMDOGlyvAJHuFYKdEDmLhi8OaGspnAsNdk/RDNFP4ZoQY2sQeyIHyLTKZAugHLQyFxJE0Yq0ulBCSnGPNBwvBZBi9teI2jCFyysuFcQ4J6nBX7NH2jlX5jTrDcHm3AkEFFr2RM3A=
